-- Gold tables store entity-resolution outputs and trusted customer master records.

use role SYSADMIN;
use database CUSTOMER360_DB;
use schema GOLD;

create table if not exists customer_match_predictions (
    match_id varchar not null,
    left_source_system varchar not null,
    left_source_customer_id varchar not null,
    right_source_system varchar not null,
    right_source_customer_id varchar not null,
    match_probability number(10, 8) not null,
    confidence_score number(10, 8) not null,
    comparison_vector variant,
    blocking_rule varchar,
    model_version varchar not null,
    predicted_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (match_id) not enforced
)
cluster by (to_date(predicted_at), match_probability)
comment = 'Pairwise Splink match predictions and comparison metadata';

create table if not exists customer_clusters (
    cluster_id varchar not null,
    golden_customer_id varchar not null,
    cluster_size number(18, 0) not null,
    representative_source_system varchar,
    representative_source_customer_id varchar,
    max_match_probability number(10, 8),
    avg_match_probability number(10, 8),
    cluster_rules array,
    model_version varchar not null,
    created_at timestamp_ntz not null default current_timestamp(),
    updated_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (cluster_id) not enforced
)
cluster by (golden_customer_id, cluster_id)
comment = 'Resolved customer clusters generated by Splink';

create table if not exists gold_customer_clusters (
    cluster_id varchar not null,
    golden_customer_id varchar not null,
    cluster_size number(18, 0) not null,
    source_members variant,
    source_customer_ids array,
    source_systems array,
    representative_source_system varchar,
    representative_source_customer_id varchar,
    max_match_probability number(10, 8),
    avg_match_probability number(10, 8),
    confidence_score number(10, 8),
    cluster_rules array,
    model_version varchar not null,
    created_at timestamp_ntz not null default current_timestamp(),
    updated_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (cluster_id) not enforced
)
cluster by (golden_customer_id, cluster_id)
comment = 'Gold-layer customer clusters generated by the Splink matching engine';

create table if not exists customer_identity_map (
    golden_customer_id varchar not null,
    cluster_id varchar not null,
    source_system varchar not null,
    source_customer_id varchar not null,
    source_record_id varchar,
    match_probability number(10, 8),
    is_primary_source boolean not null default false,
    active_from timestamp_ntz not null default current_timestamp(),
    active_to timestamp_ntz,
    is_current boolean not null default true,
    load_batch_id varchar,
    primary key (golden_customer_id, source_system, source_customer_id) not enforced
)
cluster by (source_system, source_customer_id, golden_customer_id)
comment = 'Crosswalk from source customer identifiers to golden customer identifiers';

create table if not exists gold_customer_master (
    golden_customer_id varchar not null,
    cluster_id varchar not null,
    source_customer_ids array,
    source_systems array,
    company_name varchar,
    email varchar,
    phone varchar,
    address_line_1 varchar,
    address_line_2 varchar,
    city varchar,
    state_region varchar,
    postal_code varchar,
    country varchar,
    address varchar,
    website_domain varchar,
    industry varchar,
    customer_status varchar,
    primary_source_system varchar,
    primary_source_customer_id varchar,
    first_seen_at timestamp_ntz,
    last_seen_at timestamp_ntz,
    confidence_score number(10, 8),
    completeness_score number(5, 4),
    data_quality_score number(5, 4),
    survivorship_rules variant,
    golden_record_version varchar not null default 'v1',
    is_active boolean not null default true,
    created_at timestamp_ntz not null default current_timestamp(),
    updated_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (golden_customer_id) not enforced
)
cluster by (golden_customer_id, company_name)
comment = 'Trusted golden customer records after entity resolution and survivorship';

alter table if exists gold_customer_clusters
    add column if not exists source_members variant;

alter table if exists gold_customer_master
    add column if not exists survivorship_rules variant;

create table if not exists gold_customer_enrichment (
    golden_customer_id varchar not null,
    metric_date date not null,
    lifetime_value number(18, 2),
    engagement_score number(10, 4),
    adoption_score number(10, 4),
    renewal_probability number(10, 4),
    product_usage_score number(10, 4),
    marketing_engagement_score number(10, 4),
    support_activity_score number(10, 4),
    support_ticket_count number(18, 0),
    satisfaction_score number(10, 4),
    active_users number(18, 0),
    active_days number(18, 0),
    feature_utilization_score number(10, 4),
    renewal_status varchar,
    license_expiration_date date,
    model_version varchar,
    calculated_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (golden_customer_id, metric_date) not enforced
)
cluster by (metric_date, golden_customer_id)
comment = 'Customer enrichment metrics generated after golden-record creation';

create table if not exists customer_enrichment_metrics (
    golden_customer_id varchar not null,
    metric_date date not null,
    lifetime_value number(18, 2),
    product_adoption_score number(10, 4),
    engagement_score number(10, 4),
    support_health_score number(10, 4),
    renewal_probability number(10, 4),
    product_usage_score number(10, 4),
    marketing_engagement_score number(10, 4),
    support_activity_score number(10, 4),
    support_ticket_count number(18, 0),
    satisfaction_score number(10, 4),
    response_time_minutes number(18, 4),
    active_users number(18, 0),
    active_days number(18, 0),
    feature_utilization_score number(10, 4),
    renewal_status varchar,
    license_expiration_date date,
    contract_value number(18, 2),
    seat_count number(18, 0),
    metric_components variant,
    model_version varchar,
    calculated_at timestamp_ntz not null default current_timestamp(),
    load_batch_id varchar,
    primary key (golden_customer_id, metric_date) not enforced
)
cluster by (metric_date, golden_customer_id)
comment = 'Daily customer enrichment metrics for CLV, adoption, engagement, support health, and renewal probability';

-- Optional performance enhancement for entity-resolution workloads:
-- enable Search Optimization Service on customer_identity_map(source_system, source_customer_id)
-- and gold_customer_master(email, phone, website_domain) after validating cost and edition support.
